suppressPackageStartupMessages({
  library(Seurat)
  require(withr)
  options(SeuratData.repo.use = "https://seurat-data-ran.s3.us-east-2.amazonaws.com/")
  library(SeuratData)
  library(SeuratDisk)
  library(BPCells)
  library(ggplot2)
  library(cowplot)
  library(anndata)
  library(dplyr)
  library(hdf5r)
  library(COSG)
  library(Azimuth)
  library(tidyverse)
  library(data.table)
  library(harmony)
  library(limma)
  library(scDblFinder)
  library(BiocParallel)
  library(clustree)
  library(scCustomize)
  library(viridis)
  library(RColorBrewer)
  library(gridExtra)
  library(qs)
  library(DoubletFinder)
  library(fields)
  library(KernSmooth)
  library(parallel)
  library(CellMixS)
  library(magrittr)
  library(scater)
  library(rliger)
  library(DropletUtils)
  library(here)
  library(foreach)
  library(parallel)
  library(doParallel)
  library(fishpond)
  library(SingleCellExperiment)
  library(dsb)
  library(rlang)
  library(openxlsx)
  library(pinyin)
  library(readxl)
  library(monocle3)#轨迹分析
  library(CytoTRACE2)#轨迹分析
  library(dittoSeq)#seurat出漂亮图
  library(slingshot)#轨迹分析
  library(BUSpaRse)
  library(tidymodels)
  library(scales)
  library(tradeSeq)
  library(grDevices)
  library(patchwork)
  library(R.utils)
  library(gt)
  library(glue)
  library(sceasy)
  library(sccomp)#细胞比例分析
  library(speckle)#细胞比例分析
  library(future)
  library(job)
  library(tools)
  library(snowfall)
  reticulate::use_python("/home/liyanguo/anaconda3/envs/R/bin/python")
  library(reticulate)
  #scrublet <- import("scrublet")
  #celltypist <- import("celltypist")#细胞注释
  #scanpy = import("scanpy")
  #sctour =  import("sctour")#轨迹分析
  #numpy = import("numpy")
  #pandas = import("pandas")
  set.seed(1)
})
